### ISSUE TITLE
Should hydra-integration be implemented as a plugin

### ISSUE THREAD

**Issue by ecwyne** [jkyberneees/hydra-integration#2]
Thanks so much for your phenomenal work on this package!

Please see https://github.com/ecwyne/hydra-integration-as-plugin-example

This is not working code (though it's pretty close), but just a starting point for discussion

Benefits of using hydra-integration as a plugin
- Users can setup express/hapi/koa/etc servers just like they're used to 
  - no hydra-specific configuration required
  - easier to integrate with existing code bases
- hydra-integration is not pinned to a particular version of hydra. No need to keep dependency up to date

I'd love to hear your thoughts and see if there's anything I'm totally missing!

`/lib` is where the plugin logic is
`app.js` is an example usage

**Comment by jkyberneees** [comment]
Hi @ecwyne, first off thanks a lot for your compliments on the module. 
Just in case you missed it, the hydra-integration module also support embedding mode: https://github.com/jkyberneees/hydra-integration/blob/master/docs/HydraServiceFactory.md#embedding

However, I agree with you! 
Providing a plug-in instead of a wrapping module is much more beneficial for the hydra project. 
I will properly extend it and let you know.

Thanks.

**Comment by jkyberneees** [comment]
Hi @ecwyne, from version 0.6.x the hydra-integration module is also available as a plugin, just check: https://github.com/jkyberneees/hydra-integration/blob/master/docs/HydraIntegrationPlugin.md

Thanks, Rolando.
